#!/bin/bash
shopt -s nullglob
if [[ $EUID != 0 ]] ; then
	echo This must be run as root!
	exit 1
fi
for xhci in /sys/bus/pci/drivers/?hci_hcd ; do
	if ! cd "$xhci" ; then
		echo "Failed to change directory to $xhci"
		exit 1
	fi
	echo "Resetting devices from $xhci..."
	for i in ????:??:??.? ; do
		echo -n "$i" > unbind
		echo -n "$i" > bind
	done
done
sleep 10
