name: 'Run Shellcheck'
on: [pull_request, push]

jobs:
  shellcheck:
    name: Shellcheck Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          check_all_files_with_shebangs: "false"
