#!/usr/bin/awk
BEGIN {
    FS=","
}
{
    if (split($1, a, "@") > 2) {
        printf("%s,%s", a[2], a[3])
    }
    else {
        printf("%s,%s", a[1], a[2]);
    }
    printf(",%s,%s\n", $2, $3 )
}
